Main svc
TimurDV88/java-explore-with-me pull request #4
Opened 2023-09-22 06:18 UTC by TimurDV88

2023-09-22 12:21 UTC, EugeneLenkevich requested changes
Привет, Тимур! Спасибо за PR.

Отличная работа! :)
Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста

2023-09-22 12:21 UTC, EugeneLenkevich commented on main-service/src/main/java/ru/practicum/ewm/ParticipationRequest/service/PartRequestService.java
> +    public PartRequestDto add(Long requesterId, Long eventId) {
А давай ка еще над все методы, которые изменяют данные (insert, update и delete) будем оформлять как логические транзакции, так будет правильнее. То есть добавим аннотацию @Transactional над ними

```
@Transactional
public PartRequestDto add(Long requesterId, Long eventId) {
...
```

2023-09-22 12:21 UTC, EugeneLenkevich commented on main-service/src/main/java/ru/practicum/ewm/compilation/repository/CompEventRepository.java
> +    @Query("DELETE CompEvent AS comp_event " +
А тут вроде можно было и не указывать query, имени метода достаточно должно быть, да и запрос не сложный :)

2023-09-22 12:21 UTC, EugeneLenkevich commented on stat-service/service/src/main/java/ru/practicum/ewm/service/StatService.java
>          for (String uri : uris) {
А вот тут похоже что в цикле мы делаем кучку запросов в БД, в целом это не очень оптимально по производительности.  Плюс еще и на стороне сервиса приходится результаты сортировать. А не получится ли тут сделать все это одним запросом? :)

предположу, что можно сделать в запросе group by по требуемым полям (uri?) и должен получится нужный результат)

![image](https://github.com/TimurDV88/java-explore-with-me/assets/109306643/38b97b20-7a88-4a92-abbf-1074227d9721)

2023-09-23 05:37 UTC, TimurDV88 commented on main-service/src/main/java/ru/practicum/ewm/ParticipationRequest/service/PartRequestService.java
> +    public PartRequestDto add(Long requesterId, Long eventId) {
Привет) У меня сейчас эта аннотация повешена на все контроллеры, получается, оттуда убрать и пометить только нужные методы?

2023-09-24 06:17 UTC, EugeneLenkevich commented on main-service/src/main/java/ru/practicum/ewm/ParticipationRequest/service/PartRequestService.java
> +    public PartRequestDto add(Long requesterId, Long eventId) {
Надо не контроллеры, а сервисы :)

![image](https://github.com/TimurDV88/java-explore-with-me/assets/109306643/605e696b-e62d-40f3-82dc-3baf1bfceefd)

2023-09-24 06:18 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-09-24 07:19 UTC, EugeneLenkevich commented on main-service/src/main/java/ru/practicum/ewm/ParticipationRequest/service/PartRequestService.java
> +    public PartRequestDto add(Long requesterId, Long eventId) {
На контроллерах эту аннотацию обычно не вешают. На сервисе они более логичны так как методы сервиса могут дергаться не обязательно из контроллера, потому важно чтобы он сам заботился о своих транзакциях

Так что лучше в следующий раз их с контроллеров убрать, но оставить на сервисах  :)

2023-09-25 04:57 UTC, merged